run_example: run_sh load_to_tml

run_sh:
	@echo "Running federated learning training script..."
	@./run.sh

load_to_tml:
	@echo "Loading and compiling the model with Torus ML..."
	@python load_to_tml.py
