/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 8 "luxfhe.go"

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* luxfhe_version(void);
extern void luxfhe_version_info(int* major, int* minor, int* patch);
extern char* luxfhe_error_string(int err);
extern int luxfhe_context_new(int paramSet, GoUintptr* out);
extern void luxfhe_context_free(GoUintptr ctx);
extern int luxfhe_context_params(GoUintptr ctx, int* nLWE, int* nBR, uint64_t* qLWE, uint64_t* qBR);
extern int luxfhe_keygen_secret(GoUintptr ctx, GoUintptr* out);
extern int luxfhe_keygen_public(GoUintptr ctx, GoUintptr sk, GoUintptr* out);
extern int luxfhe_keygen_bootstrap(GoUintptr ctx, GoUintptr sk, GoUintptr* out);
extern int luxfhe_keygen_all(GoUintptr ctx, GoUintptr* skOut, GoUintptr* pkOut, GoUintptr* bskOut);
extern void luxfhe_secretkey_free(GoUintptr sk);
extern void luxfhe_publickey_free(GoUintptr pk);
extern void luxfhe_bootstrapkey_free(GoUintptr bsk);
extern int luxfhe_encryptor_new_sk(GoUintptr ctx, GoUintptr sk, GoUintptr* out);
extern int luxfhe_encryptor_new_pk(GoUintptr ctx, GoUintptr pk, GoUintptr* out);
extern int luxfhe_decryptor_new(GoUintptr ctx, GoUintptr sk, GoUintptr* out);
extern int luxfhe_evaluator_new(GoUintptr ctx, GoUintptr bsk, GoUintptr sk, GoUintptr* out);
extern void luxfhe_encryptor_free(GoUintptr enc);
extern void luxfhe_decryptor_free(GoUintptr dec);
extern void luxfhe_evaluator_free(GoUintptr eval);
extern int luxfhe_encrypt_bool(GoUintptr enc, _Bool value, GoUintptr* out);
extern int luxfhe_decrypt_bool(GoUintptr dec, GoUintptr ct, _Bool* out);
extern void luxfhe_ciphertext_free(GoUintptr ct);
extern int luxfhe_ciphertext_clone(GoUintptr ct, GoUintptr* out);
extern int luxfhe_encrypt_byte(GoUintptr enc, uint8_t value, GoUintptr* out);
extern int luxfhe_decrypt_byte(GoUintptr dec, GoUintptr ct, uint8_t* out);
extern int luxfhe_not(GoUintptr eval, GoUintptr ct, GoUintptr* out);
extern int luxfhe_and(GoUintptr eval, GoUintptr ct1, GoUintptr ct2, GoUintptr* out);
extern int luxfhe_or(GoUintptr eval, GoUintptr ct1, GoUintptr ct2, GoUintptr* out);
extern int luxfhe_xor(GoUintptr eval, GoUintptr ct1, GoUintptr ct2, GoUintptr* out);
extern int luxfhe_nand(GoUintptr eval, GoUintptr ct1, GoUintptr ct2, GoUintptr* out);
extern int luxfhe_nor(GoUintptr eval, GoUintptr ct1, GoUintptr ct2, GoUintptr* out);
extern int luxfhe_xnor(GoUintptr eval, GoUintptr ct1, GoUintptr ct2, GoUintptr* out);
extern int luxfhe_mux(GoUintptr eval, GoUintptr sel, GoUintptr ctTrue, GoUintptr ctFalse, GoUintptr* out);
extern int luxfhe_and3(GoUintptr eval, GoUintptr ct1, GoUintptr ct2, GoUintptr ct3, GoUintptr* out);
extern int luxfhe_or3(GoUintptr eval, GoUintptr ct1, GoUintptr ct2, GoUintptr ct3, GoUintptr* out);
extern int luxfhe_majority(GoUintptr eval, GoUintptr ct1, GoUintptr ct2, GoUintptr ct3, GoUintptr* out);
extern void luxfhe_bytes_free(uint8_t* data);
extern int luxfhe_secretkey_serialize(GoUintptr sk, uint8_t** data, size_t* length);
extern int luxfhe_ciphertext_serialize(GoUintptr ct, uint8_t** data, size_t* length);

#ifdef __cplusplus
}
#endif
